"""French public bodies (names only, generic pictograms, evocative colours - never a real logo,
no Marianne / RF bloc-marque / coat of arms / tricolour) and the slot -> body mapping."""

# id: (ring top, ring bottom, pictogram, band colour, text colour, metal, short name for lockups)
BODIES = {
 # core set
 'urssaf':        ('URSSAF', 'COTISATIONS SOCIALES', 'euro', '#1d3f72', '#f6eed8', 'gold', 'Urssaf'),
 'caf':           ('CAISSE D’ALLOCATIONS FAMILIALES', 'CAF', 'famille', '#16639f', '#f4f1e6', 'gold', 'Caf'),
 'ameli':         ('L’ASSURANCE MALADIE', 'SÉCURITÉ SOCIALE', 'sante', '#1f4e9c', '#f4f1e6', 'silver', 'L’Assurance Maladie'),
 'dgfip':         ('DIRECTION GÉNÉRALE DES FINANCES PUBLIQUES', 'IMPÔTS', 'impots', '#16505a', '#f3ecd6', 'gold', 'Impôts'),
 'francetravail': ('FRANCE TRAVAIL', 'EMPLOI ET FORMATION', 'emploi', '#2a2f7e', '#f4f1e6', 'gold', 'France Travail'),
 'francetitres':  ('FRANCE TITRES', 'ANTS', 'identite', '#2d5596', '#f4f1e6', 'silver', 'France Titres'),
 'retraite':      ('L’ASSURANCE RETRAITE', 'SÉCURITÉ SOCIALE', 'sablier', '#9c4a1c', '#f8eedc', 'gold', 'L’Assurance retraite'),
 'servicepublic': ('SERVICE-PUBLIC', 'VOS DROITS ET DÉMARCHES', 'info', '#1f2a66', '#f4f1e6', 'gold', 'Service-Public'),
 'crous':         ('CROUS', 'VIE ÉTUDIANTE', 'education', '#a3222c', '#f8eedc', 'gold', 'Crous'),
 'msa':           ('MUTUALITÉ SOCIALE AGRICOLE', 'MSA', 'agriculture', '#356a2a', '#f3f0dc', 'gold', 'MSA'),
 'laposte':       ('LA POSTE', 'COURRIER ET COLIS', 'courrier', '#e9b91c', '#1b2a55', 'silver', 'La Poste'),
 'sncf':          ('SNCF', 'TRANSPORT FERROVIAIRE', 'transport', '#7a1c44', '#f6ebe0', 'silver', 'SNCF'),
 # extras
 'meteo':         ('MÉTÉO-FRANCE', 'PRÉVISIONS ET VIGILANCE', 'climat', '#1b68ab', '#f4f1e6', 'silver', 'Météo-France'),
 'onf':           ('OFFICE NATIONAL DES FORÊTS', 'ONF', 'nature', '#285f35', '#f1eed8', 'gold', 'Office national des forêts'),
 'parcs':         ('PARCS NATIONAUX DE FRANCE', 'NATURE PROTÉGÉE', 'montagne', '#4a6a2c', '#f3f0dc', 'gold', 'Parcs nationaux de France'),
 'ademe':         ('ADEME', 'TRANSITION ÉCOLOGIQUE', 'energie', '#127a66', '#eef6f0', 'gold', 'Ademe'),
 'cnil':          ('CNIL', 'DONNÉES PERSONNELLES', 'cadenas', '#3a2f6b', '#f2eef8', 'silver', 'CNIL'),
 'bdf':           ('BANQUE DE FRANCE', 'BANQUE CENTRALE', 'monnaie', '#152f55', '#f3e7c4', 'gold', 'Banque de France'),
 'defenseur':     ('DÉFENSEUR DES DROITS', 'ACCÈS AU DROIT', 'justice', '#4a2d72', '#f3eef8', 'gold', 'Défenseur des droits'),
 'mairie':        ('MAIRIE', 'LISTES ÉLECTORALES', 'mairie', '#1d3a6e', '#f4f1e6', 'gold', 'Mairie'),
 'douane':        ('LA DOUANE', 'VOYAGEURS ET MARCHANDISES', 'valise', '#1a2d4f', '#eef1f5', 'silver', 'La Douane'),
 'paf':           ('POLICE AUX FRONTIÈRES', 'AÉROPORTS ET PORTS', 'voyage', '#24406b', '#eef1f5', 'silver', 'Police aux frontières'),
 'assemblee':     ('ASSEMBLÉE NATIONALE', 'DÉBAT PARLEMENTAIRE', 'batiment', '#1f3868', '#f4f1e6', 'gold', 'Assemblée nationale'),
 'senat':         ('SÉNAT', 'PARLEMENT', 'batiment', '#7a1f2b', '#f6e9d6', 'gold', 'Sénat'),
 'archives':      ('ARCHIVES NATIONALES', 'MÉMOIRE ET PATRIMOINE', 'archives', '#2b2c36', '#efeee8', 'gold', 'Archives nationales'),
 'insee':         ('INSEE', 'STATISTIQUES PUBLIQUES', 'stats', '#5a2a5e', '#f5eef5', 'silver', 'Insee'),
 'bnf':           ('BIBLIOTHÈQUE NATIONALE DE FRANCE', 'BNF', 'culture', '#1d1f2a', '#f2efe6', 'gold', 'Bibliothèque nationale de France'),
 'legifrance':    ('LÉGIFRANCE', 'LE DROIT FRANÇAIS', 'archives', '#25405e', '#f4f1e6', 'gold', 'Légifrance'),
 'franceconnect': ('FRANCECONNECT', 'IDENTIFICATION EN LIGNE', 'cadenas', '#1f3f8f', '#f4f1e6', 'silver', 'FranceConnect'),
 'pharos':        ('PHAROS', 'SIGNALEMENTS EN LIGNE', 'numerique', '#1b2033', '#eef1f5', 'silver', 'Pharos'),
 'amf':           ('AUTORITÉ DES MARCHÉS FINANCIERS', 'AMF', 'stats', '#1c4d6b', '#eef4f7', 'gold', 'Autorité des marchés financiers'),
 'acpr':          ('AUTORITÉ DE CONTRÔLE PRUDENTIEL', 'ET DE RÉSOLUTION', 'monnaie', '#2e3b4e', '#eef1f5', 'silver', 'ACPR'),
 'conseiletat':   ('CONSEIL D’ÉTAT', 'JUSTICE ADMINISTRATIVE', 'batiment', '#2d3b4e', '#eef1f5', 'gold', 'Conseil d’État'),
 'conseilconst':  ('CONSEIL CONSTITUTIONNEL', 'CONTRÔLE DES ÉLECTIONS', 'vote', '#3a3150', '#f2eef8', 'gold', 'Conseil constitutionnel'),
 'justice':       ('MINISTÈRE DE LA JUSTICE', 'TRIBUNAUX', 'justice', '#0f5550', '#eef6f2', 'gold', 'Ministère de la Justice'),
 'interieur':     ('MINISTÈRE DE L’INTÉRIEUR', 'ÉLECTIONS', 'vote', '#1f3460', '#f4f1e6', 'gold', 'Ministère de l’Intérieur'),
 'viepublique':   ('VIE-PUBLIQUE', 'INSTITUTIONS ET DÉBATS', 'bulle_i', '#34405a', '#eef1f5', 'silver', 'Vie-publique'),
 'anil':          ('ANIL', 'INFORMATION LOGEMENT', 'logement', '#1f4a78', '#f4f1e6', 'gold', 'ANIL'),
 'cnes':          ('CNES', 'AGENCE SPATIALE', 'planete', '#141a33', '#eef1f8', 'silver', 'CNES'),
 'dgac':          ('DIRECTION GÉNÉRALE DE L’AVIATION CIVILE', 'DGAC', 'voyage', '#1d5a9e', '#f4f6fa', 'silver', 'DGAC'),
 'police':        ('POLICE NATIONALE', 'SÉCURITÉ PUBLIQUE', 'securite', '#1b2f5b', '#f4f1e6', 'gold', 'Police nationale'),
 'spf':           ('SANTÉ PUBLIQUE FRANCE', 'PRÉVENTION', 'sante', '#0f6360', '#eef6f2', 'gold', 'Santé publique France'),
 'ars':           ('AGENCE RÉGIONALE DE SANTÉ', 'ARS', 'sante', '#2c5e8c', '#f4f6fa', 'silver', 'Agence régionale de santé'),
 'inpi':          ('INPI', 'PROPRIÉTÉ INDUSTRIELLE', 'ampoule', '#8a3a1c', '#f8eedc', 'gold', 'INPI'),
 'art':           ('AUTORITÉ DE RÉGULATION DES TRANSPORTS', 'ART', 'transport', '#243f66', '#f4f1e6', 'gold', 'Autorité de régulation des transports'),
 'onacvg':        ('OFFICE NATIONAL DES COMBATTANTS', 'ET DES VICTIMES DE GUERRE', 'ruban', '#1c2f59', '#f4ead0', 'gold', 'ONaCVG'),
 'dae':           ('DIRECTION DES ACHATS DE L’ÉTAT', 'ACHATS PUBLICS', 'batiment', '#8a6320', '#fff4d6', 'gold', 'Direction des achats de l’État'),
 'marine':        ('MARINE NATIONALE', 'DÉFENSE', 'mer', '#16294f', '#f4ead0', 'gold', 'Marine nationale'),
 'armees':        ('MINISTÈRE DES ARMÉES', 'DÉFENSE', 'securite', '#2d3a2e', '#eef1ea', 'gold', 'Ministère des Armées'),
 'afd':           ('AGENCE FRANÇAISE DE DÉVELOPPEMENT', 'AFD', 'globe', '#0f5277', '#eef5fa', 'gold', 'Agence française de développement'),
 'travail':       ('INSPECTION DU TRAVAIL', 'SANTÉ ET SÉCURITÉ', 'emploi', '#6b5220', '#f8eedc', 'gold', 'Inspection du travail'),
 'anses':         ('ANSES', 'SÉCURITÉ SANITAIRE', 'securite', '#2a6a4a', '#eef6f0', 'gold', 'Anses'),
 'ign':           ('IGN', 'INFORMATION GÉOGRAPHIQUE', 'carte', '#0f5a7c', '#eef5fa', 'gold', 'IGN'),
 'dge':           ('DIRECTION GÉNÉRALE DES ENTREPRISES', 'DGE', 'industrie', '#24406b', '#f4f1e6', 'gold', 'DGE'),
 'asnr':          ('AUTORITÉ DE SÛRETÉ NUCLÉAIRE', 'ET DE RADIOPROTECTION', 'sciences', '#1d2233', '#eef1f5', 'silver', 'ASNR'),
 'brgm':          ('BUREAU DE RECHERCHES', 'GÉOLOGIQUES ET MINIÈRES', 'montagne', '#3a3a3f', '#efeee8', 'gold', 'BRGM'),
 'mdph':          ('MAISON DÉPARTEMENTALE', 'DES PERSONNES HANDICAPÉES', 'accessibilite', '#1d5a9e', '#f4f6fa', 'silver', 'MDPH'),
 'enfance':       ('ENFANCE EN DANGER', 'ALLÔ 119', 'famille', '#1a6a5c', '#eef6f2', 'gold', 'Allô 119'),
 'securitecivile':('SÉCURITÉ CIVILE', 'PROTECTION DES POPULATIONS', 'securite', '#8c2a1f', '#f8eedc', 'gold', 'Sécurité civile'),
 'georisques':    ('GÉORISQUES', 'RISQUES NATURELS', 'eau', '#0b4f7c', '#e8f4fb', 'silver', 'Géorisques'),
 'cada':          ('COMMISSION D’ACCÈS AUX DOCUMENTS ADMINISTRATIFS', 'CADA', 'archives', '#0f5c5a', '#eef6f2', 'gold', 'CADA'),
 'diplomatie':    ('FRANCE DIPLOMATIE', 'FRANÇAIS DE L’ÉTRANGER', 'globe', '#1c3a6b', '#f4f1e6', 'gold', 'France Diplomatie'),
 'asp':           ('AGENCE DE SERVICES ET DE PAIEMENT', 'ASP', 'euro', '#1f6b52', '#eef6f0', 'gold', 'ASP'),
 'fonctionpub':   ('FONCTION PUBLIQUE', 'DGAFP', 'emploi', '#1d3a6e', '#f4f1e6', 'gold', 'Fonction publique'),
 'bonjour':       ('BONJOUR, FRANCE', 'SITE NON OFFICIEL', 'bulle', '#8a6320', '#fff4d6', 'gold', 'Bonjour, France'),
}

# fictional local authorities (never real places) - restyled in the same family
LOCAL = {
 'seal-local-arapahoe-county': ('COMMUNAUTÉ DES VALLONS', 'INTERCOMMUNALITÉ', 'mairie', '#1d3a6e'),
 'seal-local-arizona': ('RÉGION DES CANYONS', 'TERRE DU SUD', 'montagne', '#8c3b1f'),
 'seal-local-ashland-oregon': ('VILLE DE BELLERIVE', 'MAIRIE', 'mairie', '#285f35'),
 'seal-local-boston': ('VILLE DE PORT-CLAIR', 'CITÉ MARITIME', 'mer', '#1b2033'),
 'seal-local-boulder-county': ('PAYS DES CRÊTES', 'COMMUNAUTÉ', 'montagne', '#285f35'),
 'seal-local-brookline-massachusetts': ('VILLE DE VAL-FLEURI', 'MAIRIE', 'mairie', '#6a1f2b'),
 'seal-local-colorado': ('RÉGION DES CIMES', 'MONTAGNES', 'montagne', '#1d5a9e'),
 'seal-local-columbia-county-oregon': ('PAYS DES DEUX RIVES', 'COMMUNAUTÉ', 'eau', '#0b4f7c'),
 'seal-local-cuyahoga-county': ('PAYS DE LA RIVIÈRE', 'INTERCOMMUNALITÉ', 'mairie', '#1d3a6e'),
 'seal-local-florida': ('RÉGION DU LITTORAL', 'TERRE DE SOLEIL', 'climat', '#0b4f7c'),
 'seal-local-henderson-county-north-carolina': ('PAYS DES COLLINES', 'COMMUNAUTÉ DE COMMUNES', 'montagne', '#285f35'),
 'seal-local-maricopa-county': ('PAYS DU PLATEAU', 'COMMUNAUTÉ', 'climat', '#8c3b1f'),
 'seal-local-maryland': ('RÉGION DES BAIES', 'LITTORAL', 'mer', '#6a1f2b'),
 'seal-local-minnesota': ('RÉGION DES LACS', 'TERRE D’EAU', 'eau', '#1d5a9e'),
 'seal-local-nebraska': ('RÉGION DES PLAINES', 'TERRE AGRICOLE', 'agriculture', '#8c3b1f'),
 'seal-local-north-dakota': ('RÉGION DU NORD', 'CHAMPS ET PRAIRIES', 'agriculture', '#356a2a'),
 'seal-local-ohio': ('RÉGION DES VALLÉES', 'COMMUNES UNIES', 'mairie', '#1d3a6e'),
 'seal-local-oregon': ('RÉGION DES FORÊTS', 'TERRE VERTE', 'nature', '#285f35'),
 'seal-local-redmond-washington': ('VILLE DE CLAIRMONT', 'MAIRIE', 'mairie', '#0f5550'),
 'seal-local-rialto-california': ('VILLE DE SAINT-ARLET', 'MAIRIE', 'mairie', '#8c3b1f'),
 'seal-local-texas': ('RÉGION DU GRAND SUD', 'TERRE DE SOLEIL', 'climat', '#1c2f59'),
 'seal-local-washington': ('RÉGION DES PINS', 'TERRE D’OUEST', 'nature', '#0f5550'),
}
for k, (t, b, p, c) in LOCAL.items():
    BODIES['local:' + k] = (t, b, p, c, '#f4f1e6', 'gold', t.title().replace('De ', 'de ').replace('Des ', 'des ').replace('Du ', 'du ').replace('La ', 'la ').replace('D’', 'd’'))

# slot key (inventory base name) -> body id
SLOTS = {
 # zone a grid (3x3 SVGs) + manifesto stack
 'seal-treasury': 'dgfip', 'seal-veterans-affairs': 'ameli', 'seal-commerce': 'urssaf',
 'seal-interior': 'msa', 'social-security-older': 'caf', 'labor': 'francetravail',
 'seal-patent-and-trademark-office': 'servicepublic', 'transportation': 'sncf', 'seal-energy': 'crous',
 'seal-state': 'laposte',
 # zone c name-change card
 'government-social-security-seal': 'retraite', 'state.gov': 'francetitres', 'cbp': 'douane', 'seal-tsa': 'paf',
 'name-change-irs': 'dgfip', 'name-change-ssa': 'retraite', 'name-change-state': 'francetitres',
 'ssa.gov': 'retraite', 'cbp.gov': 'douane',
 # other home seals
 'congress': 'senat', 'house': 'assemblee', 'dea': 'spf', 'energy': 'ademe', 'faa': 'dgac', 'fbi': 'police',
 'forest-service': 'onf', 'great-seal': 'bonjour', 'hud': 'anil', 'library-of-congress': 'bnf',
 'patent-and-trademark': 'inpi', 'surface-transportation-board': 'art', 'treasury': 'dgfip',
 'us-marshals': 'justice', 'government-veterans-affairs-seal': 'onacvg', 'gsa-gold-seal': 'dae',
 'medicare-seal': 'ameli', 'veterans-crisis-line-seal': 'onacvg', 'employment-navy': 'marine', 'navy': 'marine',
 'gsa': 'dae', 'nasa': 'cnes',
 # agency seals
 'seal-administrative-conference-of-the-united-states': 'conseiletat',
 'seal-customs-and-border-protection': 'douane',
 'seal-development-finance-corporation': 'afd',
 'seal-federal-mine-safety-and-health-review-commission': 'travail',
 'seal-geographic-names-board': 'ign',
 'seal-industry-and-security-bureau': 'dge',
 'seal-inter-american-foundation': 'afd',
 'seal-legal-services-corporation': 'defenseur',
 'seal-national-credit-union-administration': 'bdf',
 'seal-nuclear-regulatory-commission': 'asnr',
 'seal-occupational-safety-and-health-review-commission': 'anses',
 'seal-surface-mining-reclamation-and-enforcement-office': 'brgm',
 'seal-united-states-courts': 'justice',
 # chat source chips (favicons of agency sites)
 'fallback-ada.gov': 'mdph', 'fallback-archives.gov': 'archives', 'fallback-cbp.gov': 'douane',
 'fallback-census.gov': 'insee', 'fallback-childcare.gov': 'caf', 'fallback-childwelfare.gov': 'enfance',
 'fallback-congress.gov': 'assemblee', 'fallback-copyright.gov': 'inpi', 'fallback-data.census.gov': 'insee',
 'fallback-disasterassistance.gov': 'securitecivile', 'fallback-eac.gov': 'mairie', 'fallback-fec.gov': 'conseilconst',
 'fallback-federalregister.gov': 'legifrance', 'fallback-floodsmart.gov': 'georisques', 'fallback-foia.gov': 'cada',
 'fallback-fvap.gov': 'diplomatie', 'fallback-grants.gov': 'asp', 'fallback-gsa.gov': 'dae',
 'fallback-healthcare.gov': 'ameli', 'fallback-house.gov': 'assemblee', 'fallback-hrsa.gov': 'ars',
 'fallback-ic3.gov': 'pharos', 'fallback-identitytheft.gov': 'cnil', 'fallback-ihs.gov': 'spf',
 'fallback-insurekidsnow.gov': 'ameli', 'fallback-investor.gov': 'amf', 'fallback-login.gov': 'franceconnect',
 'fallback-medicaid.gov': 'ameli', 'fallback-medicare.gov': 'retraite', 'fallback-milconnect.dmdc.osd.mil': 'armees',
 'fallback-ncua.gov': 'bdf', 'fallback-occ.gov': 'acpr', 'fallback-opm.gov': 'fonctionpub',
 'fallback-pbgc.gov': 'retraite', 'fallback-recreation.gov': 'parcs', 'fallback-sam.gov': 'dae',
 'fallback-sec.gov': 'amf', 'fallback-senate.gov': 'senat', 'fallback-studentaid.gov': 'crous',
 'fallback-tsa.gov': 'paf', 'fallback-usa.gov': 'bonjour', 'fallback-usajobs.gov': 'francetravail',
 'fallback-uscourts.gov': 'justice', 'fallback-uspto.gov': 'inpi', 'fallback-vote.gov': 'interieur',
 'fallback-weather.gov': 'meteo', 'fallback-whitehouse.gov': 'viepublique',
}
for k in LOCAL:
    SLOTS[k] = 'local:' + k
